from __future__ import annotations

CATEGORIES = frozenset(("QUALITY", "VALUE", "MOMENTUM", "GROWTH", "CAPITAL_ALLOCATION", "BALANCE_SHEET", "PROFITABILITY", "SENTIMENT", "MACRO", "TECHNICAL", "THESIS", "RISK", "CUSTOM"))